POST http://localhost:3003/user/create 
Content-Type: application/json

{
    "name": "Gabriel Oliveira",
    "email": "gabriel@gmail.com",
    "password": "123456qws"
}


###
POST http://localhost:3003/posts/create
Content-Type: application/json

{
    "photo": "https://img.freepik.com/fotos-gratis/bela-foto-de-um-corpo-d-agua-com-ondas-do-mar_181624-29582.jpg?w=996&t=st=1666455292~exp=1666455892~hmac=27d95c79946981edd64de6c370790be6f7715741efbdf324a48e9869179faeaf",
    "description": "A mar...",
    "type": "normal",
    "author_id": "3e199805-56f9-4c9f-bf33-c8c936c962b5"

}


###
GET http://localhost:3003/posts/get/39cd67eb-8289-44fa-a6f9-eae9ea3ca504